// frontend/components/ui/Button.jsx
import clsx from 'clsx'
import Link from 'next/link'

export default function Button({ href = '#', variant = 'primary', className = '', children }) {
  const classes = clsx(
    'inline-flex items-center justify-center rounded-full border px-5 py-2.5 text-sm font-semibold transition duration-300 will-change-transform',
    'hover:scale-[1.03] active:scale-[0.98] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-red-500 focus-visible:ring-offset-2 focus-visible:ring-offset-black',
    {
      'border-red-500 bg-red-500 text-white shadow-[0_10px_35px_rgba(225,6,0,0.35)] hover:bg-red-600 hover:border-red-600': variant === 'primary',
      'border-white/35 bg-white/5 text-white backdrop-blur-md hover:border-white/60 hover:bg-white/10 hover:shadow-[0_8px_28px_rgba(255,255,255,0.18)]': variant === 'secondary',
    },
    className,
  )

  return (
    <Link href={href} className={classes}>
      {children}
    </Link>
  )
}

// frontend/src/components/ui/Button.vue
<template>
  <component :is="tag" v-bind="componentProps" :class="buttonClass">
    <slot />
  </component>
</template>

<script setup>
import clsx from 'clsx'
import { computed } from 'vue'
import { RouterLink } from 'vue-router'

const props = defineProps({
  variant: {
    type: String,
    default: 'primary',
  },
  type: {
    type: String,
    default: 'button',
  },
  to: {
    type: String,
    default: '',
  },
  href: {
    type: String,
    default: '',
  },
})

const tag = computed(() => {
  if (props.to) return RouterLink
  if (props.href) return 'a'
  return 'button'
})

const componentProps = computed(() => {
  if (props.to) return { to: props.to }
  if (props.href) return { href: props.href, target: '_blank', rel: 'noreferrer' }
  return { type: props.type }
})

const buttonClass = computed(() =>
  clsx(
    'inline-flex items-center justify-center rounded-lg border px-4 py-2 text-sm font-medium transition-all duration-200 focus:outline-none focus:ring-2 focus:ring-red-500',
    {
      'border-red-500 bg-red-500 text-white hover:border-red-600 hover:bg-red-600': props.variant === 'primary',
      'border-white/70 bg-transparent text-white hover:border-red-500 hover:text-red-500': props.variant === 'secondary',
      'border-transparent bg-transparent text-gray-400 hover:text-red-500': props.variant === 'ghost',
    },
  ),
)
</script>
